<?php

namespace MADB\Main;

/** Shows and executes SQL generated by menu/editor actions. */
class GeneratedQueryController extends ScreenController {

  private static array $state = [];

  /** Opens the generated SQL preview panel. */
  public static function open(array $state): void {
    self::$state = array_merge([
      'title' => 'Generated query',
      'name' => 'Generated query',
      'sql' => '',
      'connection' => false,
      'schema' => false,
      'executionSchema' => false,
      'table' => false,
      'expectsResult' => false,
      'allowNoRefreshRun' => false,
      'refreshQueryId' => false,
      'cacheKeys' => [],
      'refresh' => false,
      'directCommand' => false,
      'directArguments' => [],
      'confirmation' => false,
      'confirmed' => false,
      'pendingRefreshAfterRun' => true
    ], $state);
    self::showPanel(self::$state['title'], self::$state['sql'], self::$state['allowNoRefreshRun']);
  }

  /** Runs generated SQL and refreshes related result/menu state. */
  public static function runAndRefresh($panel = null): void {
    self::syncSql($panel);
    if (!self::validateState()) {
      return;
    }
    if (self::confirmBeforeRun($panel, true)) {
      return;
    }
    if (!empty(self::$state['expectsResult'])) {
      self::openInEditor($panel, true);
      return;
    }
    self::runDirect(true);
  }

  /** Runs generated SQL without refreshing the source result. */
  public static function runNoRefresh($panel = null): void {
    if (empty(self::$state['allowNoRefreshRun'])) {
      return;
    }
    self::syncSql($panel);
    if (!self::validateState()) {
      return;
    }
    if (self::confirmBeforeRun($panel, false)) {
      return;
    }
    self::runDirect(false);
  }

  /** Runs the generated SQL after a confirmation panel has been accepted. */
  public static function runConfirmed($confirmationPanel): void {
    $values = $confirmationPanel->getValue();
    if (!isset($values['confirmed']) || $values['confirmed'] !== true) {
      return;
    }
    $confirmationPanel->remove();
    self::$state['confirmed'] = true;
    if (!empty(self::$state['expectsResult'])) {
      self::openInEditor(null, true);
      return;
    }
    self::runDirect(!empty(self::$state['pendingRefreshAfterRun']));
  }

  /** Opens generated SQL in a normal query tab. */
  public static function openInEditor($panel = null, bool $execute = false): void {
    self::syncSql($panel);
    if (!self::validateState()) {
      return;
    }
    if ($panel !== null && method_exists($panel, 'remove')) {
      $panel->remove();
    }
    \MADB\Main\ScreenController::addQuery(
      self::$state['name'],
      self::$state['sql'],
      self::$state['connection']['name'],
      self::$state['schema'],
      self::$state['table']
    );
    if ($execute) {
      \MADB\Main\QueryExecutionController::executeQuery();
    }
  }

  /** Closes the generated SQL panel. */
  public static function close($panel): void {
    self::$state = [];
    $panel->remove();
    \SPTK\Element::refresh();
  }

  /** Handles direct non-result SQL execution results. */
  public static function directResult($response): void {
    if (($response['status'] ?? '') === 'PROGRESS') {
      return;
    }
    $state = $response['generatedQuery'] ?? self::$state;
    if ($response['status'] !== 'OK') {
      self::showError((string)$response['result']);
      return;
    }
    $result = is_array($response['result']) ? $response['result'] : [];
    $error = self::batchError($result);
    if ($error !== false) {
      self::showError($error);
      return;
    }
    self::clearCache($state);
    $refresh = !empty($state['refreshAfterRun']);
    if ($refresh) {
      self::refreshAfterRun($state);
    }
    $lines = self::statusLines($result);
    self::removePanel();
    self::showStatus('Query completed', implode("\n", $lines));
  }

  /** Displays generated SQL preview panel. */
  private static function showPanel(string $titleText, string $sql, bool $allowNoRefreshRun): void {
    self::removePanel();
    $window = \SPTK\Element::firstByType('Window');
    if ($window === false) {
      return;
    }
    $panel = new \SPTK\Elements\Panel($window, 'generated-query-preview');
    $title = new \SPTK\Element($panel, null, null, 'PanelTitle');
    $title->addText($titleText);
    $content = new \SPTK\Element($panel, null, null, 'PanelContent');
    $preview = new \SPTK\Elements\TextBox($content, 'generated-query-sql');
    $preview->setTokenizer(false);
    $preview->setValue($sql);
    new \SPTK\Element($content, 'generated-query-status', null, 'Box');
    $buttons = new \SPTK\Element($content, null, null, 'ButtonBox');
    self::addButton($buttons, 'RETURN', 'MADB\Main\GeneratedQueryController::runAndRefresh', 'Run', 'generated-query-run');
    if ($allowNoRefreshRun) {
      new \SPTK\Elements\Space($buttons);
      self::addButton($buttons, 'F3', 'MADB\Main\GeneratedQueryController::runNoRefresh', 'Run only');
    }
    new \SPTK\Elements\Space($buttons);
    self::addButton($buttons, 'F4', 'MADB\Main\GeneratedQueryController::openInEditor', 'Editor');
    new \SPTK\Elements\Space($buttons);
    self::addButton($buttons, 'ESCAPE', 'MADB\Main\GeneratedQueryController::close', 'Cancel');
    $panel->show();
    if (method_exists($panel, 'activateInput')) {
      $panel->activateInput('generated-query-run');
    }
    \SPTK\Element::refresh();
  }

  /** Runs the generated SQL directly through the connection engine. */
  private static function runDirect(bool $refreshAfterRun): void {
    self::$state['refreshAfterRun'] = $refreshAfterRun;
    if (!empty(self::$state['directCommand'])) {
      \MADB\Job\JobHandler::startJob([
        'connection' => self::$state['connection'],
        'command' => self::$state['directCommand'],
        'arguments' => self::$state['directArguments'] ?? [],
        'callback' => ['\MADB\Main\GeneratedQueryController', 'directResult'],
        'generatedQuery' => self::$state
      ]);
      return;
    }
    $statements = \MADB\Query\SqlSplitter::split(self::$state['sql']);
    foreach ($statements as $index => $statement) {
      $statements[$index]['index'] = $index;
    }
    \MADB\Job\JobHandler::startJob([
      'connection' => self::$state['connection'],
      'command' => 'queryBatch',
      'arguments' => [$statements, [], self::$state['executionSchema'] ?? false],
      'callback' => ['\MADB\Main\GeneratedQueryController', 'directResult'],
      'generatedQuery' => self::$state
    ]);
  }

  /** Opens a confirmation panel before executing sensitive generated SQL. */
  private static function confirmBeforeRun($panel, bool $refreshAfterRun): bool {
    if (empty(self::$state['confirmation']) || !empty(self::$state['confirmed'])) {
      return false;
    }
    self::$state['pendingRefreshAfterRun'] = $refreshAfterRun;
    $confirmation = self::$state['confirmation'];
    $title = is_array($confirmation) ? ($confirmation['title'] ?? 'Run query') : 'Run query';
    $content = is_array($confirmation) ? ($confirmation['content'] ?? 'Run this generated query?') : (string)$confirmation;
    \SPTK\Elements\WarningPanel::forge(
      $title,
      $content,
      [
        ['text' => 'Run', 'hotKey' => 'RETURN', 'onPress' => '\MADB\Main\GeneratedQueryController::runConfirmed'],
        ['text' => 'Cancel', 'hotKey' => 'ESCAPE', 'onPress' => 'close']
      ]
    );
    \SPTK\Element::refresh();
    return true;
  }

  /** Updates SQL state from the preview textbox. */
  private static function syncSql($panel): void {
    if ($panel === null || !method_exists($panel, 'getValue')) {
      return;
    }
    $values = $panel->getValue();
    if (isset($values['generated-query-sql'])) {
      self::$state['sql'] = self::textValue($values['generated-query-sql']);
    }
  }

  /** Validates generated SQL state before executing or opening it. */
  private static function validateState(): bool {
    if (empty(self::$state['connection']) || trim((string)self::$state['sql']) === '') {
      \SPTK\Elements\WarningPanel::forge('No query', 'There is no generated query to run.');
      return false;
    }
    return true;
  }

  /** Clears metadata cache entries described by generated SQL state. */
  private static function clearCache(array $state): void {
    $connection = $state['connection']['name'] ?? false;
    if ($connection === false) {
      return;
    }
    foreach (($state['cacheKeys'] ?? []) as $key) {
      \MADB\Job\Cache::clear($connection, $key);
    }
  }

  /** Refreshes result or menus after a direct generated SQL run. */
  private static function refreshAfterRun(array $state): void {
    if (!empty($state['refreshQueryId']) && !empty($state['connection']['name'])) {
      \MADB\Main\ScreenController::executeQueryById($state['connection']['name'], $state['refreshQueryId']);
      return;
    }
    if (($state['refresh'] ?? false) === 'schemas' && !empty($state['connection']['name'])) {
      \MADB\Connection\MenuController::select($state['connection']['name']);
      return;
    }
    if (($state['refresh'] ?? false) === 'tables' && !empty($state['schema'])) {
      \MADB\Schema\MenuController::select($state['schema']);
    }
  }

  /** Shows direct execution status inside the generated query panel. */
  private static function showStatus(string $title, string $text): void {
    $panel = \SPTK\Element::byName('generated-query-preview');
    if ($panel === false) {
      \SPTK\Elements\Panel::forge($title, $text);
      return;
    }
    $status = \SPTK\Element::byName('generated-query-status', $panel);
    if ($status !== false) {
      $status->setText($text);
    }
    \SPTK\Element::refresh();
  }

  /** Shows direct execution failure while keeping the generated SQL panel open. */
  private static function showError(string $text): void {
    self::showStatus('Query failed', $text);
    \SPTK\Elements\ErrorPanel::forge('Query failed', $text);
  }

  /** Returns a direct batch execution error message, if any. */
  private static function batchError(array $result) {
    foreach (($result['statements'] ?? []) as $statement) {
      if (($statement['status'] ?? '') === 'ERROR') {
        return 'Query failed: ' . ($statement['error'] ?? 'Unknown error');
      }
    }
    return false;
  }

  /** Builds status text for direct generated SQL execution. */
  private static function statusLines(array $result): array {
    if (isset($result['statements']) && is_array($result['statements'])) {
      $lines = ['Query completed.'];
      foreach ($result['statements'] as $index => $statement) {
        $prefix = 'Statement ' . ((int)$index + 1) . ': OK';
        $statementResult = is_array($statement['result'] ?? false) ? $statement['result'] : [];
        if (isset($statementResult['affectedRows'])) {
          $prefix .= ', affected rows: ' . (int)$statementResult['affectedRows'];
        } else if (isset($statementResult['rowCount'])) {
          $prefix .= ', rows: ' . (int)$statementResult['rowCount'];
        } else if (isset($statementResult['rows'])) {
          $prefix .= ', rows: ' . count((array)$statementResult['rows']);
        }
        $lines[] = $prefix;
      }
      return $lines;
    }
    $lines = ['Query completed.'];
    if (isset($result['affectedRows'])) {
      $lines[] = 'Affected rows: ' . (int)$result['affectedRows'];
    } else if (isset($result['rows'])) {
      $lines[] = 'Rows returned: ' . count((array)$result['rows']);
    }
    return $lines;
  }

  /** Adds a hotkey button to a dynamic panel. */
  private static function addButton($parent, string $hotKey, string $callback, string $text, string $name = null): void {
    $button = new \SPTK\Elements\Button($parent, $name);
    $button->setHotKey($hotKey);
    $button->setOnPress($callback);
    $button->addText($text);
  }

  /** Removes any existing generated query panel. */
  private static function removePanel(): void {
    $panel = \SPTK\Element::byName('generated-query-preview');
    if ($panel !== false) {
      $panel->remove();
    }
  }

  /** Returns plain text from SPTK values. */
  private static function textValue($value): string {
    if (is_array($value)) {
      return implode("\n", $value);
    }
    return (string)$value;
  }

}
